external-controller: 127.0.0.1:33243
log-level: silent
mixed-port: 55817
port: 60843
proxies:
- cipher: ss
  name: "13|\u65E5\u672C4|@ripaojiedian"
  network: tcp
  password: //Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTo4OWQ1MjUxNC1mNWE0LTQ1YzYtOTZlYS00OWUxMTNlNjAxMjk
  port: 10007
  server: 183.2.133.119
  skip-cert-verify: false
  tls: false
  type: ss
  udp: true
proxy-groups:
- name: test-group
  proxies:
  - "13|\u65E5\u672C4|@ripaojiedian"
  type: select
socks-port: 53371
unified-delay: true
