external-controller: 127.0.0.1:44707
log-level: silent
mixed-port: 40393
port: 58949
proxies:
- cipher: ss
  name: "13|tg\u9891\u9053:@ripaojiedian #1"
  network: tcp
  password: //YWVzLTI1Ni1jZmI6YW1hem9uc2tyMDU
  port: 443
  server: 3.9.17.198
  skip-cert-verify: false
  tls: false
  type: ss
  udp: true
proxy-groups:
- name: test-group
  proxies:
  - "13|tg\u9891\u9053:@ripaojiedian #1"
  type: select
socks-port: 37313
unified-delay: true
