external-controller: 127.0.0.1:53113
log-level: silent
mixed-port: 39825
port: 33437
proxies:
- cipher: ss
  name: "13|\u8D8A\u5357|@ripaojiedian"
  network: tcp
  password: //YWVzLTI1Ni1jZmI6WG44aktkbURNMDBJZU8lIyQjZkpBTXRzRUFFVU9wSC9ZV1l0WXFERm5UMFNW
  port: 38388
  server: 103.186.155.215
  skip-cert-verify: false
  tls: false
  type: ss
  udp: true
proxy-groups:
- name: test-group
  proxies:
  - "13|\u8D8A\u5357|@ripaojiedian"
  type: select
socks-port: 60429
unified-delay: true
